// <auto-generated />
using System;
using Game.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Game.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260817164631_AddPlayerDeploymentReady")]
    partial class AddPlayerDeploymentReady
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Game.Domain.Entities.GameMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActivePlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_player_id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("turn_number");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid?>("WinnerPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_player_id");

                    b.HasKey("Id");

                    b.ToTable("game_matches", (string)null);
                });

            modelBuilder.Entity("Game.Domain.Entities.GamePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsReady")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_ready");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<int>("Seat")
                        .HasColumnType("integer")
                        .HasColumnName("seat");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "Seat")
                        .IsUnique();

                    b.ToTable("game_players", (string)null);
                });

            modelBuilder.Entity("Game.Domain.Entities.GameUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Column")
                        .HasColumnType("integer")
                        .HasColumnName("column");

                    b.Property<bool>("HasAttackedThisTurn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_attacked_this_turn");

                    b.Property<int>("Health")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("health");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid>("OwnerPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_player_id");

                    b.Property<int>("RemainingMovement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("remaining_movement");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasDefaultValue("Infantry")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "Column", "Row")
                        .IsUnique();

                    b.ToTable("game_units", (string)null);
                });

            modelBuilder.Entity("Game.Domain.Entities.GamePlayer", b =>
                {
                    b.HasOne("Game.Domain.Entities.GameMatch", null)
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Game.Domain.Entities.GameUnit", b =>
                {
                    b.HasOne("Game.Domain.Entities.GameMatch", null)
                        .WithMany("Units")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Game.Domain.Entities.GameMatch", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
