// <auto-generated />
using System;
using Game.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Game.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260827143946_AddReconnaissance")]
    partial class AddReconnaissance
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Game.Domain.Entities.EnemySighting", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Column")
                        .HasColumnType("integer")
                        .HasColumnName("column");

                    b.Property<Guid>("EnemyUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("enemy_unit_id");

                    b.Property<int>("LastSeenTurnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("last_seen_turn_number");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<string>("UnitType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("unit_type");

                    b.Property<Guid>("ViewerPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("viewer_player_id");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "ViewerPlayerId", "EnemyUnitId")
                        .IsUnique();

                    b.ToTable("game_enemy_sightings", (string)null);
                });

            modelBuilder.Entity("Game.Domain.Entities.GameMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActivePlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("active_player_id");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid?>("RematchMatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("rematch_match_id");

                    b.Property<Guid?>("RematchRequestedByPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("rematch_requested_by_player_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("TurnExpiresAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("turn_expires_at_utc");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("turn_number");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.Property<Guid?>("WinnerPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("winner_player_id");

                    b.HasKey("Id");

                    b.HasIndex("Status", "TurnExpiresAtUtc");

                    b.ToTable("game_matches", (string)null);
                });

            modelBuilder.Entity("Game.Domain.Entities.GameMatchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_player_id");

                    b.Property<int?>("Amount")
                        .HasColumnType("integer")
                        .HasColumnName("amount");

                    b.Property<int?>("FromColumn")
                        .HasColumnType("integer")
                        .HasColumnName("from_column");

                    b.Property<int?>("FromRow")
                        .HasColumnType("integer")
                        .HasColumnName("from_row");

                    b.Property<int>("FromVisibleToSeats")
                        .HasColumnType("integer")
                        .HasColumnName("from_visible_to_seats");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid?>("RelatedPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("related_player_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<Guid?>("TargetUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_unit_id");

                    b.Property<string>("TargetUnitType")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("target_unit_type");

                    b.Property<int?>("ToColumn")
                        .HasColumnType("integer")
                        .HasColumnName("to_column");

                    b.Property<int?>("ToRow")
                        .HasColumnType("integer")
                        .HasColumnName("to_row");

                    b.Property<int>("ToVisibleToSeats")
                        .HasColumnType("integer")
                        .HasColumnName("to_visible_to_seats");

                    b.Property<int>("TurnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("turn_number");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("unit_id");

                    b.Property<string>("UnitType")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("unit_type");

                    b.Property<bool>("WasDestroyed")
                        .HasColumnType("boolean")
                        .HasColumnName("was_destroyed");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "Sequence")
                        .IsUnique();

                    b.ToTable("game_match_events", (string)null);
                });

            modelBuilder.Entity("Game.Domain.Entities.GamePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsReady")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_ready");

                    b.Property<DateTimeOffset>("JoinedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("joined_at_utc");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("name");

                    b.Property<int>("Seat")
                        .HasColumnType("integer")
                        .HasColumnName("seat");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "Seat")
                        .IsUnique();

                    b.ToTable("game_players", (string)null);
                });

            modelBuilder.Entity("Game.Domain.Entities.GameSpecialTile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Column")
                        .HasColumnType("integer")
                        .HasColumnName("column");

                    b.Property<bool>("IsRevealed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_revealed");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid?>("RevealedByUnitId")
                        .HasColumnType("uuid")
                        .HasColumnName("revealed_by_unit_id");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "Column", "Row")
                        .IsUnique();

                    b.ToTable("game_special_tiles", (string)null);
                });

            modelBuilder.Entity("Game.Domain.Entities.GameUnit", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Column")
                        .HasColumnType("integer")
                        .HasColumnName("column");

                    b.Property<bool>("HasAttackedThisTurn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("has_attacked_this_turn");

                    b.Property<int>("Health")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4)
                        .HasColumnName("health");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("match_id");

                    b.Property<Guid>("OwnerPlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_player_id");

                    b.Property<int>("RemainingMovement")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("remaining_movement");

                    b.Property<int?>("RevealedUntilTurnNumber")
                        .HasColumnType("integer")
                        .HasColumnName("revealed_until_turn_number");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<string>("Type")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasDefaultValue("Infantry")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "Column", "Row")
                        .IsUnique();

                    b.ToTable("game_units", (string)null);
                });

            modelBuilder.Entity("Game.Domain.Entities.EnemySighting", b =>
                {
                    b.HasOne("Game.Domain.Entities.GameMatch", null)
                        .WithMany("EnemySightings")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Game.Domain.Entities.GameMatchEvent", b =>
                {
                    b.HasOne("Game.Domain.Entities.GameMatch", null)
                        .WithMany("Events")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Game.Domain.Entities.GamePlayer", b =>
                {
                    b.HasOne("Game.Domain.Entities.GameMatch", null)
                        .WithMany("Players")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Game.Domain.Entities.GameSpecialTile", b =>
                {
                    b.HasOne("Game.Domain.Entities.GameMatch", null)
                        .WithMany("SpecialTiles")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Game.Domain.Entities.GameUnit", b =>
                {
                    b.HasOne("Game.Domain.Entities.GameMatch", null)
                        .WithMany("Units")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Game.Domain.Entities.GameMatch", b =>
                {
                    b.Navigation("EnemySightings");

                    b.Navigation("Events");

                    b.Navigation("Players");

                    b.Navigation("SpecialTiles");

                    b.Navigation("Units");
                });
#pragma warning restore 612, 618
        }
    }
}
